//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCSharp.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.OrderLineItems = new HashSet<OrderLineItem>();
        }
    
        public int BookId { get; set; }
        public int BookTypeId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> PublisherId { get; set; }
        public string Title { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Summary { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ISBN { get; set; }
        public Nullable<int> UnitsInStock { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> UnitsOnOrder { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLineItem> OrderLineItems { get; set; }
    }
}
