//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCSharp.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLineItem
    {
        public long OrderLineItemId { get; set; }
        public long OrderId { get; set; }
        public int BookId { get; set; }
        public decimal UnitPrice { get; set; }
        public int Quantity { get; set; }
        public decimal UnitPriceDiscount { get; set; }
        public decimal LineTotal { get; set; }
        public string TrackingNumber { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Order Order { get; set; }
    }
}
